# Generated by Django 4.2.7 on 2023-11-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_skills_volunteersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='mail',
            field=models.EmailField(default='hello@reallygreatsite.com', max_length=254),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
