# Generated by Django 4.2.7 on 2023-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_landingpage_facebook_landingpage_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='profile_pic',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='profile/'),
        ),
    ]
