# Generated by Django 4.2.7 on 2023-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_landingpage_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussection',
            name='cover_pic_for_aboutme',
            field=models.FileField(default=None, null=True, upload_to='aboutme/'),
        ),
        migrations.AddField(
            model_name='volunteersection',
            name='volunteer_cover_pic',
            field=models.FileField(default=None, null=True, upload_to='volunteer/'),
        ),
    ]
